project_id = "prmxceldmgubfduczbop"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.cubicasa-gotoscan]
verify_jwt = false

[functions.cubicasa-webhook]
verify_jwt = false